### ISSUE TITLE
Todo List 1

### ISSUE THREAD

**Issue by JamenMarz** [Tunnelled/Server#2]
- [x] Design protocol v1
  - [x] Header / frame
    - [x] Purpose (1 byte)
    - [x] Target ID (4 bytes)
    - [x] Payload (varies)

- [ ] Modular ([/lib](https://github.com/Tunnelled/Server/tree/master/lib))
  - [ ] Reading socket headers.
  - [ ] I/O

**Comment by JamenMarz** [comment]
Project dead for the time being.
